### PR TITLE
Fixes for 1.2 release

### LINKED ISSUE #7: Unable to edit comments
When you edit comments from the WordPress dashboard, and then click the "Update Comment" button, there's a "Are you sure you want to do this?Please try again" error message.

We've replicated the issue in several environments. Deactivating the comment hacks plugin resolves the issue so it appears this may be a bug. Let me know if you need any additional details. I'm happy to provide any additional info I can. Thanks.

editing-comments

### LINKED ISSUE #8: Comment type missing from clean email
In the cleaned email, the comment type is not displayed, resulting in messages like:

  A new on the post "Post Title Goes Here" is waiting for your approval:

The message should read, "A new **comment** on the post..."

### LINKED ISSUE #10: Unable to set comment_parent to 0
Hi, I'm testing this plugin and I've found this:

Bugs:
- Setting the comment_parent as 0 does not work, neither leaving the field empty. Sometimes users post comments as replies to other comment, but they are not related. Currently, I manually set the comment_parent in the DB to 0.

Improvements:
- add the Comment Parent field in the Quick Edit too.
- I like the Clean emails idea, but it would be nice to have the option to add the author IP since it gives information about author location.
- the only way to email all commenters is if the user has "Show Toolbar when viewing site" enabled. I personally disable that, and there is no other way to use your feature. You should add it in the post links, like you do with individual emails.
- add i18n support (WPML) for the min length error message.

### LINKED ISSUE #14: Unable to disable clean comments
See thread here: https://wordpress.org/support/topic/cant-turn-of-clean-comment-emails/

### PR DESCRIPTION
**Pull request by jdevalk**
Fixes several issues:

* Differentiate between AJAX request and normal POST for nonce checking, fixes #7.
* Make sure comment_type isn't empty, fixes #8.
* Allow setting the comment parent to 0, fixes #10.
* Prevents defaults from being reinstated, fixes #14.

Also:

* Adds translator comments to all strings with `sprintf` / `printf`.
* Updates to new version of Yoast i18n, in the process switching from `translate.yoast.com` to `translate.wordpress.org` and removing packaged translations.
* Updates version number to 1.2 and updates changelog in `readme.txt`.
* Added `yarn.lock` and removed no longer needed i18n grunt tasks.

### CODE REVIEW

File: inc/class-clean-emails.php [hunk 1]
```diff
@@ -86,6 +87,11 @@ public function comment_notification_text( $message, $comment_id ) {
 	public function comment_moderation_text( $message, $comment_id ) {
 		$this->setup_data( $comment_id );
 
+		if ( empty( $this->comment->comment_type ) ) {
+			$this->comment->comment_type = __( 'comment', 'yoast-comment-hacks' );
```
Comment (afercia) [inline inc/class-clean-emails.php]: Seems to me now that this sets the comment type to "comment", the checks in `add_author_line()` and `add_content_line()` will use the "Website" and "Excerpt" strings, and the moderation email will have a wrong content:
screen shot 2017-02-21 at 12 19 07

File: inc/class-clean-emails.php [hunk 2]
```diff
@@ -86,6 +87,11 @@ public function comment_notification_text( $message, $comment_id ) {
...
+		}
+
+		/* translators: %1$s is replaced with the comment type, %2$s is replace with the post title */
 		$this->message = sprintf( __( 'A new %1$s on the post "%2$s" is waiting for your approval:', 'yoast-comment-hacks' ), $this->comment->comment_type, '<a href="' . get_permalink( $this->comment->comment_post_ID ) . '">' . esc_html( $this->post->post_title ) . '</a>' ) . '<br /><br />';
```
Comment (afercia) [inline inc/class-clean-emails.php]: As a best practice, WordPress avoids to use post/comment types as placeholder values since this would make translations difficult in some cases. For example, `%1$s` can be replaced by comment/pingback/trackback and in some languages they could be words with a different genre, making impossible to correctly translate "new". I'd suggest a `switch` statement and split this in 3 different strings:
`A new trackback ...`
`A new pingback ...`
`A new comment ...`
Ideally, the same should be done for `comment_notification_text()`.

File: inc/class-clean-emails.php [hunk 3]
```diff
@@ -113,9 +119,11 @@ private function add_comment_basics() {
 	 */
 	private function add_author_line() {
 		if ( '' === $this->comment->comment_type ) {
```
Comment (afercia) [inline inc/class-clean-emails.php]: See comment above, this check now fails for the moderation email.

**Comment by jdevalk** [comment]
thx @afercia, fixed! Any more comments?

File: inc/class-clean-emails.php (hunk 3 above)
Comment (jdevalk) [inline inc/class-clean-emails.php]: Fixed by not changing it anymore :)

**Comment by afercia** [comment]
@jdevalk maybe one changelog entry should be changed now:
`* Make sure comment_type isn't empty, fixes #8.`

Other than that, phpcs warns a few file miss a new line at the end of the file. About composer and yarn stuff I declare my shameful ignorance :)
